### ISSUE TITLE
膜拜侯博

### ISSUE THREAD

**Issue by Han40** [marquistj13/explore_seg#1]
github怎么发私信？？？

**Comment by marquistj13** [comment]
啊，就这么发啊，我这个都failed了你还在这说风凉话

**Comment by marquistj13** [comment]
学生会员到期了，赶紧都public了

**Comment by Han40** [comment]
不public  就会丢失吗？

**Comment by marquistj13** [comment]
不public就会被lock，要么交钱要么public才能解锁，所以提前public，省的人家制裁我 
:innocent:
